// <auto-generated />
namespace TSAR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sanj03042017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sanj03042017));
        
        string IMigrationMetadata.Id
        {
            get { return "201704022226042_sanj03042017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
